# Generated by Django 5.1.15 on 2026-05-20 15:48

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0003_planversion_studyevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=1024)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lab.labfolder')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_folders', to='planner.workspace')),
            ],
            options={
                'db_table': 'lab_folder',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('active_file_ids', models.JSONField(blank=True, default=list)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_sessions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_sessions', to='planner.workspace')),
            ],
            options={
                'db_table': 'lab_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('citations', models.JSONField(blank=True, default=list)),
                ('structured_result', models.JSONField(blank=True, null=True)),
                ('tool_trace', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='lab.labsession')),
            ],
            options={
                'db_table': 'lab_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('file_key', models.CharField(max_length=1024)),
                ('mime_type', models.CharField(max_length=100)),
                ('extension', models.CharField(blank=True, max_length=32)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('index_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('upload', 'Upload'), ('artifact', 'Artifact'), ('import', 'Import')], default='upload', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_files', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_files', to='planner.workspace')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='lab.labfolder')),
                ('source_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifact_files', to='lab.labsession')),
            ],
            options={
                'db_table': 'lab_file',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_chunks', to='planner.workspace')),
                ('lab_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='lab.labfile')),
            ],
            options={
                'db_table': 'lab_chunk',
                'ordering': ['chunk_index'],
                'indexes': [models.Index(fields=['workspace', 'lab_file'], name='lab_chunk_workspa_2647a8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='labfolder',
            constraint=models.UniqueConstraint(fields=('workspace', 'path'), name='lab_folder_workspace_path_uniq'),
        ),
    ]
