# Generated by Django 5.1.15 on 2026-05-20 17:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_pg_trgm_lab_chunk'),
        ('planner', '0003_planversion_studyevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('source_type', models.CharField(choices=[('zip', 'Zip'), ('git', 'Git')], max_length=10)),
                ('source_label', models.CharField(max_length=500)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lab_import',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='labimport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labimport',
            name='root_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='lab.labfolder'),
        ),
        migrations.AddField(
            model_name='labimport',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_imports', to='planner.workspace'),
        ),
    ]
