/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sağlık kontrolü */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Genel yapılandırma (auth gerekmez) */
        get: operations["getPublicConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kapalı beta bekleme listesi */
        post: operations["joinWaitlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Abonelik ve kota özeti */
        get: operations["getBillingMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stripe Checkout oturumu (mock destekli) */
        post: operations["createBillingCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stripe müşteri portalı */
        post: operations["createBillingPortal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feature flag listesi (auth) */
        get: operations["getFeatureFlags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback/ai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AI plan veya chat için thumbs up/down */
        post: operations["submitAIFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** E-posta ile kayıt */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** E-posta ile giriş */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Google ID Token ile giriş veya kayıt
         * @description React tarafında Google Identity Services ile alınan `id_token` gönderilir.
         *     Backend token'ı Google ile doğrular; kullanıcıyı `sub` ile bulur veya oluşturur.
         */
        post: operations["googleAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Oturum açıkken Google hesabını bağla */
        post: operations["googleLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Access token yenile */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh token iptal */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oturum açmış kullanıcı profili */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        /** Hesabı ve tüm verileri sil */
        delete: operations["deleteCurrentUser"];
        options?: never;
        head?: never;
        /** Profil ve tercihleri güncelle (locale, theme, timezone, …) */
        patch: operations["updateCurrentUser"];
        trace?: never;
    };
    "/users/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kullanıcı verisi dışa aktarımı (JSON) */
        get: operations["exportCurrentUserData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace listesi */
        get: operations["listWorkspaces"];
        put?: never;
        /** Workspace oluştur */
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspace_id}/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ders listesi */
        get: operations["listSubjects"];
        put?: never;
        /** Ders ekle */
        post: operations["createSubject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspace_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Takvim etkinlikleri (aralık) */
        get: operations["listStudyEvents"];
        put?: never;
        /** Manuel etkinlik oluştur */
        post: operations["createStudyEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Etkinlik sil */
        delete: operations["deleteStudyEvent"];
        options?: never;
        head?: never;
        /** Etkinlik güncelle (sürükle-bırak, durum) */
        patch: operations["updateStudyEvent"];
        trace?: never;
    };
    "/workspaces/{workspace_id}/plans/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mevcut haftayı plan olarak kaydet */
        post: operations["savePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan versiyonu detayı (etkinliklerle) */
        get: operations["getPlanVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/versions/{version_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Planı aktif yap */
        post: operations["activatePlanVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspace_id}/plans/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AI plan üret (async) */
        post: operations["generatePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Async görev durumu */
        get: operations["getTaskStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Başarısız veya takılı plan görevini yeniden dene */
        post: operations["retryTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspace_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Not listesi */
        get: operations["listNotes"];
        put?: never;
        /** Not oluştur */
        post: operations["createNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNote"];
        put?: never;
        post?: never;
        delete: operations["deleteNote"];
        options?: never;
        head?: never;
        patch: operations["updateNote"];
        trace?: never;
    };
    "/workspaces/{workspace_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kütüphane dosya listesi */
        get: operations["listDocuments"];
        put?: never;
        /** Yüklenen dosya metadata kaydı (index job tetikler) */
        post: operations["createDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspace_id}/documents/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Presigned PUT URL (MinIO / S3) */
        post: operations["createDocumentUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dosya durumu */
        get: operations["getDocument"];
        put?: never;
        post?: never;
        /** Dosya ve chunk silme */
        delete: operations["deleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspace_id}/retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Vektör retrieval (RAG) */
        post: operations["retrieveChunks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mesaj geçmişi */
        get: operations["listChatMessages"];
        put?: never;
        /** Mesaj gönder (RAG destekli sync) */
        post: operations["sendChatMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspace_id}/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat oturumu başlat */
        post: operations["createChatSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Desteklenen arayüz dilleri (MVP)
         * @example tr
         * @enum {string}
         */
        Locale: "tr" | "en";
        /**
         * @description light / dark — sabit tema.
         *     system — işletim sistemi tercihini izle (frontend uygular).
         * @example system
         * @enum {string}
         */
        Theme: "light" | "dark" | "system";
        /** @enum {string} */
        AuthProvider: "email" | "google";
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "degraded";
            checks: {
                [key: string]: {
                    /** @enum {string} */
                    status?: "ok" | "error";
                    detail?: string;
                };
            };
        };
        UserDataExport: {
            /** Format: date-time */
            exported_at?: string;
            user?: Record<string, never>;
            workspaces?: Record<string, never>[];
        };
        PublicConfig: {
            locales: components["schemas"]["LocaleOption"][];
            themes: components["schemas"]["ThemeOption"][];
            default_locale: components["schemas"]["Locale"];
            default_theme: components["schemas"]["Theme"];
            google_oauth: {
                enabled: boolean;
                /** @description Web client ID (public, frontend GIS için) */
                client_id: string;
            };
            feature_flags?: {
                [key: string]: boolean;
            };
        };
        BillingSummary: {
            /** @enum {string} */
            tier?: "free" | "pro";
            status?: string;
            /** Format: date-time */
            current_period_end?: string | null;
            limits?: Record<string, never>;
            usage?: Record<string, never>;
        };
        AIFeedbackCreate: {
            /** @enum {string} */
            target_type: "plan_version" | "chat_message";
            /** Format: uuid */
            target_id: string;
            /** @enum {string} */
            rating: "up" | "down";
            comment?: string;
        };
        LocaleOption: {
            code: components["schemas"]["Locale"];
            /** @example Türkçe */
            label: string;
        };
        ThemeOption: {
            code: components["schemas"]["Theme"];
            /** @example Sistem */
            label: string;
        };
        UserPreferences: {
            locale?: components["schemas"]["Locale"];
            theme?: components["schemas"]["Theme"];
            /** @example Europe/Istanbul */
            timezone?: string;
            /** @description Pomodoro süresi, uyku saatleri vb. */
            study_preferences?: {
                /** @default 25 */
                pomodoro_minutes: number;
            } & {
                [key: string]: unknown;
            };
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name?: string | null;
            /** Format: uri */
            avatar_url?: string | null;
            locale: components["schemas"]["Locale"];
            theme: components["schemas"]["Theme"];
            timezone: string;
            auth_provider: components["schemas"]["AuthProvider"];
            /** @default false */
            email_verified: boolean;
            onboarding_completed: boolean;
            study_preferences?: {
                [key: string]: unknown;
            };
            /** @description Bağlı harici hesaplar (şifre gösterilmez) */
            social_accounts?: components["schemas"]["SocialAccountSummary"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        SocialAccountSummary: {
            /** @enum {string} */
            provider: "google";
            /** Format: date-time */
            linked_at: string;
        };
        UserUpdateRequest: {
            display_name?: string;
            locale?: components["schemas"]["Locale"];
            theme?: components["schemas"]["Theme"];
            timezone?: string;
            study_preferences?: {
                [key: string]: unknown;
            };
            onboarding_completed?: boolean;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            display_name?: string;
            locale?: components["schemas"]["Locale"];
            theme?: components["schemas"]["Theme"];
            timezone?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        GoogleAuthRequest: {
            /** @description Google Identity Services credential JWT */
            id_token: string;
            /** @description İlk kayıtta varsayılan dil (yoksa Accept-Language) */
            locale?: components["schemas"]["Locale"];
            theme?: components["schemas"]["Theme"];
            /** @description IANA timezone; yoksa UTC veya frontend tahmini */
            timezone?: string;
        };
        RefreshRequest: {
            /** @description Refresh token */
            refresh: string;
        };
        TokenPair: {
            access: string;
            refresh: string;
            /**
             * @description Saniye cinsinden access token ömrü
             * @example 900
             */
            access_expires_in: number;
        };
        AuthResponse: {
            user: components["schemas"]["User"];
            tokens: components["schemas"]["TokenPair"];
            /** @description Google veya kayıt akışında yeni hesap oluşturuldu mu */
            is_new_user?: boolean;
        };
        ErrorEnvelope: {
            error: {
                /** @enum {string} */
                code: "VALIDATION_ERROR" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "RATE_LIMITED" | "ACCOUNT_EXISTS_LINK_REQUIRED" | "GOOGLE_TOKEN_INVALID" | "PLAN_GENERATION_FAILED";
                /** @description İnsan okunur; Accept-Language ile lokalize edilebilir */
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        Workspace: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            owner_id: string;
            /** Format: date */
            exam_date?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        WorkspaceCreate: {
            name: string;
            /** Format: date */
            exam_date?: string;
        };
        Subject: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspace_id: string;
            name: string;
            difficulty: number;
            /** Format: float */
            weekly_target_hours?: number | null;
            color: string;
        };
        SubjectCreate: {
            name: string;
            difficulty: number;
            weekly_target_hours?: number;
            color: string;
        };
        /** @enum {string} */
        StudyMethod: "pomodoro" | "active_recall" | "spaced_review" | "deep_reading" | "practice_exam" | "research";
        /** @enum {string} */
        StudyEventStatus: "planned" | "done" | "skipped";
        /** @enum {string|null} */
        UserFeedback: "easy" | "hard" | null;
        StudyEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspace_id: string;
            /** Format: uuid */
            subject_id?: string | null;
            /** Format: uuid */
            plan_version_id?: string | null;
            title: string;
            /** Format: date-time */
            start_at: string;
            /** Format: date-time */
            end_at: string;
            method: components["schemas"]["StudyMethod"];
            status: components["schemas"]["StudyEventStatus"];
            user_feedback?: components["schemas"]["UserFeedback"];
        };
        StudyEventCreate: {
            /** Format: uuid */
            subject_id?: string;
            title: string;
            /** Format: date-time */
            start_at: string;
            /** Format: date-time */
            end_at: string;
            method: components["schemas"]["StudyMethod"];
            status?: components["schemas"]["StudyEventStatus"];
        };
        StudyEventUpdate: {
            /** Format: uuid */
            subject_id?: string | null;
            title?: string;
            /** Format: date-time */
            start_at?: string;
            /** Format: date-time */
            end_at?: string;
            method?: components["schemas"]["StudyMethod"];
            status?: components["schemas"]["StudyEventStatus"];
            user_feedback?: components["schemas"]["UserFeedback"];
        };
        EventOverlapWarning: {
            /** @enum {string} */
            code?: "EVENT_OVERLAP";
            message?: string;
            /** Format: uuid */
            event_id?: string;
            title?: string;
        };
        StudyEventResponse: components["schemas"]["StudyEvent"] & {
            warnings?: components["schemas"]["EventOverlapWarning"][];
        };
        PlanVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspace_id: string;
            /** @enum {string} */
            generated_by: "ai" | "user";
            is_active: boolean;
            /** Format: date */
            range_start?: string | null;
            /** Format: date */
            range_end?: string | null;
            event_count?: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        PlanVersionDetail: components["schemas"]["PlanVersion"] & {
            events?: components["schemas"]["StudyEvent"][];
        };
        PlanSaveRequest: {
            /** Format: date */
            range_start: string;
            /** Format: date */
            range_end: string;
            /** @default true */
            link_events: boolean;
        };
        PlanGenerateRequest: {
            /** Format: date */
            range_start: string;
            /** Format: date */
            range_end: string;
            constraints?: {
                max_hours_per_day?: number;
                blocked_slots?: {
                    /** Format: date-time */
                    start: string;
                    /** Format: date-time */
                    end: string;
                }[];
            };
            /** @default true */
            use_rag: boolean;
        };
        AsyncTaskAccepted: {
            /** Format: uuid */
            task_id: string;
            /** @enum {string} */
            status: "pending";
            /** @example /api/v1/tasks/550e8400-e29b-41d4-a716-446655440000 */
            poll_url: string;
        };
        AsyncTask: {
            /** Format: uuid */
            task_id: string;
            /** @enum {string} */
            status: "pending" | "success" | "failed";
            result?: {
                /** Format: uuid */
                plan_version_id?: string;
            } | null;
            error?: components["schemas"]["ErrorEnvelope"];
        };
        NoteSummary: {
            /** Format: uuid */
            id?: string;
            title?: string;
            /** Format: uuid */
            subject_id?: string | null;
            /** Format: date-time */
            updated_at?: string;
        };
        Note: components["schemas"]["NoteSummary"] & {
            /** Format: uuid */
            workspace_id?: string;
            /** @description TipTap document JSON */
            content_json?: Record<string, never>;
            /** Format: date-time */
            indexed_at?: string | null;
        };
        NoteCreate: {
            title?: string;
            /** Format: uuid */
            subject_id?: string;
        };
        NoteUpdate: {
            title?: string;
            content_json?: Record<string, never>;
            /** Format: uuid */
            subject_id?: string;
        };
        UploadUrlRequest: {
            filename: string;
            /** @enum {string} */
            mime_type: "application/pdf" | "text/plain" | "text/markdown";
            size_bytes: number;
        };
        UploadUrlResponse: {
            /** Format: uri */
            upload_url?: string;
            file_key?: string;
            expires_in?: number;
        };
        DocumentCreate: {
            file_key: string;
            original_filename: string;
            /** @enum {string} */
            mime_type: "application/pdf" | "text/plain" | "text/markdown";
            size_bytes: number;
            /** Format: uuid */
            subject_id?: string | null;
        };
        Document: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            workspace_id?: string;
            /** Format: uuid */
            subject_id?: string | null;
            original_filename?: string;
            mime_type?: string;
            size_bytes?: number;
            /** @enum {string} */
            status?: "pending" | "processing" | "ready" | "failed";
            error_message?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        RetrieveRequest: {
            query: string;
            /** @default 8 */
            top_k: number;
            /** Format: uuid */
            subject_id?: string | null;
            source_types?: ("document" | "note" | "performance")[];
        };
        RetrievedChunk: {
            /** Format: uuid */
            id?: string;
            text?: string;
            /** Format: float */
            score?: number;
            /** @enum {string} */
            source_type?: "document" | "note" | "performance";
            /** Format: uuid */
            document_id?: string | null;
            /** Format: uuid */
            note_id?: string | null;
            metadata?: Record<string, never>;
            excerpt?: string;
        };
        RetrieveResponse: {
            query?: string;
            results?: components["schemas"]["RetrievedChunk"][];
        };
        ChatSession: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            workspace_id?: string;
            /** Format: date-time */
            created_at?: string;
        };
        ChatMessageContext: {
            /** Format: uuid */
            note_id?: string | null;
            /** Format: uuid */
            subject_id?: string | null;
            /** @default true */
            use_rag: boolean;
            /** @default false */
            use_grounding: boolean;
        };
        ChatMessageCreate: {
            content: string;
            context?: components["schemas"]["ChatMessageContext"];
        };
        ChatMessage: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            role?: "user" | "assistant";
            content?: string;
            citations?: components["schemas"]["ChatCitation"][];
            /** Format: date-time */
            created_at?: string;
        };
        ChatCitation: {
            /** @enum {string} */
            type?: "chunk";
            /** Format: uuid */
            chunk_id?: string;
            source_type?: string;
            /** Format: uuid */
            document_id?: string | null;
            /** Format: uuid */
            note_id?: string | null;
            excerpt?: string;
        };
        ChatMessageResponse: {
            message?: {
                /** Format: uuid */
                id?: string;
                /** @enum {string} */
                role?: "assistant";
                content?: string;
            };
            citations?: components["schemas"]["ChatCitation"][];
        };
    };
    responses: {
        /** @description Doğrulama hatası */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Kimlik doğrulama gerekli veya geçersiz token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Kaynak bulunamadı */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /**
         * @description İstenen dil. `tr` veya `en` (BCP 47 kısaltılır).
         *     Hata mesajları ve opsiyonel sunucu metinleri için.
         */
        AcceptLanguage: components["schemas"]["Locale"];
        WorkspaceId: string;
        TaskId: string;
        NoteId: string;
        DocumentId: string;
        EventId: string;
        VersionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tüm bağımlılıklar sağlıklı */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description En az bir bağımlılık hatalı (degraded) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    getPublicConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Desteklenen diller, temalar, OAuth client hint */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicConfig"];
                };
            };
        };
    };
    joinWaitlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    locale?: string;
                };
            };
        };
        responses: {
            /** @description E-posta zaten listede */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kayıt alındı */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBillingMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tier, limits, usage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingSummary"];
                };
            };
        };
    };
    createBillingCheckout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Checkout URL */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createBillingPortal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Portal URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFeatureFlags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flag anahtarları */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submitAIFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AIFeedbackCreate"];
            };
        };
        responses: {
            /** @description Kaydedildi */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description İstenen dil. `tr` veya `en` (BCP 47 kısaltılır).
                 *     Hata mesajları ve opsiyonel sunucu metinleri için.
                 */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Kayıt başarılı */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description E-posta zaten kayıtlı */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description İstenen dil. `tr` veya `en` (BCP 47 kısaltılır).
                 *     Hata mesajları ve opsiyonel sunucu metinleri için.
                 */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Giriş başarılı */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    googleAuth: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description İstenen dil. `tr` veya `en` (BCP 47 kısaltılır).
                 *     Hata mesajları ve opsiyonel sunucu metinleri için.
                 */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleAuthRequest"];
            };
        };
        responses: {
            /** @description Mevcut Google hesabı — giriş */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Yeni kullanıcı oluşturuldu */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Geçersiz veya süresi dolmuş Google token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Aynı e-posta farklı provider ile kayıtlı */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "ACCOUNT_EXISTS_LINK_REQUIRED",
                     *         "message": "Bu e-posta zaten kayıtlı. Hesabınıza Google bağlamak için giriş yapın.",
                     *         "details": {
                     *           "link_endpoint": "/api/v1/auth/google/link"
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    googleLink: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description İstenen dil. `tr` veya `en` (BCP 47 kısaltılır).
                 *     Hata mesajları ve opsiyonel sunucu metinleri için.
                 */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleAuthRequest"];
            };
        };
        responses: {
            /** @description Google hesabı bağlandı */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Google hesabı başka kullanıcıya bağlı */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Yeni token çifti */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Çıkış yapıldı */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description İstenen dil. `tr` veya `en` (BCP 47 kısaltılır).
                 *     Hata mesajları ve opsiyonel sunucu metinleri için.
                 */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    confirm: "DELETE";
                };
            };
        };
        responses: {
            /** @description Hesap silindi */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    updateCurrentUser: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description İstenen dil. `tr` veya `en` (BCP 47 kısaltılır).
                 *     Hata mesajları ve opsiyonel sunucu metinleri için.
                 */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description Güncellenmiş profil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    exportCurrentUserData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kullanıcı ve workspace verilerinin JSON dökümü */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDataExport"];
                };
            };
        };
    };
    listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        results: components["schemas"]["Workspace"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreate"];
            };
        };
        responses: {
            /** @description Oluşturuldu */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listSubjects: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dersler */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        results: components["schemas"]["Subject"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subject"];
                };
            };
        };
    };
    listStudyEvents: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        results: components["schemas"]["StudyEvent"][];
                    };
                };
            };
        };
    };
    createStudyEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyEventCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyEventResponse"];
                };
            };
        };
    };
    deleteStudyEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Silindi */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateStudyEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyEventUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyEventResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    savePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanSaveRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanVersion"];
                };
            };
        };
    };
    getPlanVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanVersionDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    activatePlanVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanVersion"];
                };
            };
        };
    };
    generatePlan: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description İstenen dil. `tr` veya `en` (BCP 47 kısaltılır).
                 *     Hata mesajları ve opsiyonel sunucu metinleri için.
                 */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path: {
                workspace_id: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanGenerateRequest"];
            };
        };
        responses: {
            /** @description Görev kuyruğa alındı */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncTaskAccepted"];
                };
            };
        };
    };
    getTaskStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncTask"];
                };
            };
        };
    };
    retryTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncTask"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listNotes: {
        parameters: {
            query?: {
                /** @description Tam metin arama (başlık + içerik) */
                q?: string;
                /** @description Derse göre filtre */
                subject_id?: string;
            };
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        results?: components["schemas"]["NoteSummary"][];
                    };
                };
            };
        };
    };
    createNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NoteCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
        };
    };
    getNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: components["parameters"]["NoteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
        };
    };
    deleteNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: components["parameters"]["NoteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Silindi */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: components["parameters"]["NoteId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NoteUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
        };
    };
    listDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        results?: components["schemas"]["Document"][];
                    };
                };
            };
        };
    };
    createDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Aynı file_key ile kayıt mevcut */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    createDocumentUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadUrlRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadUrlResponse"];
                };
            };
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Silindi */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    retrieveChunks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrieveRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrieveResponse"];
                };
            };
        };
    };
    listChatMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        results?: components["schemas"]["ChatMessage"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    sendChatMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageCreate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    createChatSession: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description İstenen dil. `tr` veya `en` (BCP 47 kısaltılır).
                 *     Hata mesajları ve opsiyonel sunucu metinleri için.
                 */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path: {
                workspace_id: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
        };
    };
}
