# Generated by Django 5.1.15 on 2026-05-19 16:14

import apps.notes.tiptap
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0003_planversion_studyevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('content_json', models.JSONField(default=apps.notes.tiptap.empty_document)),
                ('content_plain', models.TextField(blank=True, default='')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='planner.subject')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='planner.workspace')),
            ],
            options={
                'db_table': 'notes_note',
                'ordering': ['-updated_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='notes_note_search__2ae846_gin'), models.Index(fields=['workspace', '-updated_at'], name='notes_note_workspa_4aa4bb_idx')],
            },
        ),
    ]
