# Generated by Django 5.1.15 on 2026-05-19 16:21

import django.db.models.deletion
import pgvector.django
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        ('planner', '0003_planversion_studyevent'),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_key', models.CharField(max_length=1024)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='planner.subject')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='planner.workspace')),
            ],
            options={
                'db_table': 'indexer_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndexerChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('document', 'Document'), ('note', 'Note'), ('performance', 'Performance')], max_length=20)),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='indexer.document')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indexer_chunks', to='notes.note')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexer_chunks', to='planner.workspace')),
            ],
            options={
                'db_table': 'indexer_chunk',
                'ordering': ['chunk_index'],
                'indexes': [
                    models.Index(fields=['workspace', 'source_type'], name='indexer_chu_workspa_17f3e9_idx'),
                    models.Index(fields=['document'], name='indexer_chu_documen_a9e226_idx'),
                    models.Index(fields=['note'], name='indexer_chu_note_id_0942bc_idx'),
                ],
            },
        ),
    ]
