# Generated by Django 5.1.15 on 2026-05-19 16:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_by', models.CharField(choices=[('ai', 'AI'), ('user', 'User')], max_length=10)),
                ('prompt_snapshot', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('range_start', models.DateField(blank=True, null=True)),
                ('range_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_versions', to='planner.workspace')),
            ],
            options={
                'db_table': 'planner_plan_version',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('method', models.CharField(choices=[('pomodoro', 'Pomodoro'), ('active_recall', 'Active recall'), ('spaced_review', 'Spaced review'), ('deep_reading', 'Deep reading'), ('practice_exam', 'Practice exam'), ('research', 'Research')], max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('done', 'Done'), ('skipped', 'Skipped')], default='planned', max_length=10)),
                ('user_feedback', models.CharField(blank=True, choices=[('easy', 'Easy'), ('hard', 'Hard')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_events', to='planner.planversion')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_events', to='planner.subject')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_events', to='planner.workspace')),
            ],
            options={
                'db_table': 'planner_study_event',
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['workspace', 'start_at', 'end_at'], name='planner_stu_workspa_dbf22a_idx')],
            },
        ),
    ]
